/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hospitalmanagement;

import java.awt.Color;
import java.awt.Font;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTextField;
import javax.swing.border.LineBorder;

/**
 *
 * @author Hp
 */
public class up_pres extends javax.swing.JFrame {

    /**
     * Creates new form doctor_loged
     */
    String dname;

    public up_pres(String name) {
        initComponents();
        dname = name;
        prob.setEditable(false);

        jLabel2.setVisible(false);
        System.out.println(dname);
        setpats();
    }

    public void addholder(JTextField txt) {
        Font font = txt.getFont();
        font = font.deriveFont(Font.ITALIC);
        txt.setFont(font);
        txt.setForeground(Color.BLACK);
    }

    public void removeholder(JTextField txt) {
        Font font = txt.getFont();
        font = font.deriveFont(Font.PLAIN | Font.BOLD);
        txt.setFont(font);
        txt.setForeground(Color.white);
    }

    public void setpats() {
        BufferedReader br = null;
        try {
            String line;
            br = new BufferedReader(new FileReader("patients.csv"));
            while ((line = br.readLine()) != null) {
                String values[] = line.split(",");
                if (values[3].equals(dname)) {
                    pat_name.addItem(values[0] + "," + values[1]);
                }
            }
        } catch (FileNotFoundException ex) {
            this.setVisible(false);
            new update(this, rootPaneCheckingEnabled, "no Doctors Exists", WIDTH);
        } catch (IOException ex) {
            this.setVisible(false);
            new update(this, rootPaneCheckingEnabled, "no Doctors Exists", WIDTH);
        } finally {
            try {
                br.close();
            } catch (IOException ex) {
                this.setVisible(false);
                new update(this, rootPaneCheckingEnabled, "no Doctors Exists", WIDTH);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pres = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        prob = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        pat_name = new javax.swing.JComboBox<>();
        enter = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pres.setBackground(new java.awt.Color(29, 164, 196));
        pres.setColumns(20);
        pres.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pres.setForeground(new java.awt.Color(255, 255, 255));
        pres.setRows(5);
        jScrollPane1.setViewportView(pres);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, 290, 210));

        prob.setBackground(new java.awt.Color(29, 164, 196));
        prob.setColumns(20);
        prob.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        prob.setForeground(new java.awt.Color(255, 255, 255));
        prob.setRows(5);
        jScrollPane2.setViewportView(prob);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 290, 210));

        jButton1.setBackground(new java.awt.Color(29, 164, 196));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Update");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 410, 110, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Precription Updated");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 410, 200, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Disease");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 160, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Prescription");
        jLabel4.setToolTipText("");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 160, -1));

        jButton2.setBackground(new java.awt.Color(29, 164, 196));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Back");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 100, 40));

        pat_name.setBackground(new java.awt.Color(29, 164, 196));
        pat_name.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pat_name.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(pat_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 70, 180, 40));

        enter.setBackground(new java.awt.Color(29, 164, 196));
        enter.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        enter.setForeground(new java.awt.Color(255, 255, 255));
        enter.setText("enter");
        enter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enterMouseClicked(evt);
            }
        });
        getContentPane().add(enter, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 70, 110, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hospitalmanagement/Best-FreeOpen-Source-Hospital-Management-System-02-1.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setPreferredSize(new java.awt.Dimension(1100, 520));
        jLabel1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jLabel1FocusGained(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jLabel1FocusGained
        jLabel1.requestFocus();

    }//GEN-LAST:event_jLabel1FocusGained

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_formFocusGained

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        this.requestFocus();
    }//GEN-LAST:event_formWindowGainedFocus
    public void update(String value[]) {
        System.out.println(value[0] + "," + value[1] + "," + value[2]);
        String line;

        try {
            File newfile = new File("temp.csv");
            File oldfile = new File("pres.csv");
            FileWriter fw = new FileWriter(newfile, true);
            BufferedWriter bw = new BufferedWriter(fw);
            PrintWriter pw = new PrintWriter(bw);

            BufferedReader br = new BufferedReader(new FileReader("pres.csv"));
            while ((line = br.readLine()) != null) {
                String values[] = line.split(",");
                if (values[0].equals(id)) {
                    pw.println(value[0] + "," + value[1] + "," + value[2]);
                } else {
                    pw.println(line);
                }

            }
            pw.flush();
            pw.close();
            br.close();
            bw.close();
            fw.close();
            System.out.println("updated");
            String xx = oldfile.getAbsolutePath();

            oldfile.delete();

            if (oldfile.exists()) {
                System.out.println("not deleted");
            }
            File dump = new File(xx);

            newfile.renameTo(dump);
            jLabel2.setVisible(true);
        } catch (IOException ex) {
            System.out.println("yayan se");
            Logger.getLogger(up_pres.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        BufferedReader br2 = null;
        String x = id;
        String value[] = null;
        try {

            br2 = new BufferedReader(new FileReader("pres.csv"));
            String line2;
            while ((line2 = br2.readLine()) != null) {
                String values2[] = line2.split(",");
                if (values2[0].equals(x)) {
                    values2[2] = pres.getText();
                    System.out.println(values2[2]);
                    value = values2;
                    break;
                }
            }
            br2.close();
            update(value);

        } catch (FileNotFoundException ex) {
            System.out.println("idher se");
            Logger.getLogger(up_pres.class.getName()).log(Level.SEVERE, null, ex);

        } catch (IOException ex) {
            Logger.getLogger(up_pres.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        this.setVisible(false);
        new doctor_logged(dname).setVisible(true);
    }//GEN-LAST:event_jButton2MouseClicked

    private void enterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterMouseClicked
        try {
            check();
        } catch (IOException ex) {
            Logger.getLogger(up_pres.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_enterMouseClicked
    public String id;

    public void check() throws FileNotFoundException, IOException {
        String pats = (String) pat_name.getSelectedItem();
        String pat[] = pats.split(",");
        id = pat[0];
        BufferedReader br2 = new BufferedReader(new FileReader("pres.csv"));
        String line2;
        while ((line2 = br2.readLine()) != null) {
            String values2[] = line2.split(",");
            if (values2[0].equals(id)) {
                prob.setText(values2[1]);
                pres.setText(values2[2]);
            }
        }
        br2.close();

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(up_pres.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(up_pres.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(up_pres.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(up_pres.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new up_pres("").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton enter;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> pat_name;
    private javax.swing.JTextArea pres;
    private javax.swing.JTextArea prob;
    // End of variables declaration//GEN-END:variables
}
